[workspace]
resolver = "2"

members = ["day-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
nom = "7.1.3"
itertools = "0.12.0"
regex = "1.10.2"
rstest = "0.18.2"
